#!/usr/bin/env sh
set -eu

wget https://raw.githubusercontent.com/somebodykot/lmde_encryption_mirror/refs/heads/main/grub-install /mnt/tmp/
# Chroot 
mount --bind /dev /mnt/dev/
mount --bind /dev/pts /mnt/dev/pts
mount --bind /proc /mnt/proc
mount --bind /sys  /mnt/sys
mount --bind /run  /mnt/run
# Internet resolv
mount --bind /etc/resolv.conf /mnt/etc/resolv.conf

echo "After chroot, enter command: cd /tmp; bash grub-install 1"
chroot /mnt

if [ "$1" == 1 ] ; then
cd /tmp

echo "Installing build packages"
apt install -y gnulib libdevmapper-dev libfreetype-dev gettext autogen git bison help2man texinfo efibootmgr libisoburn1 libisoburn-dev mtools pkg-config m4 libtool automake autoconf flex fuse3 libfuse3-dev gawk

# mawk gives make error, so using gawk
mv /usr/bin/mawk /usr/bin/mawk_bu
ln -s /usr/bin/gawk /usr/bin/mawk

# git clone needed repos
git clone https://github.com/olafhering/grub.git # mirror https://git.savannah.gnu.org/git/grub.git
cd grub
git clone https://github.com/somebodykot/grub-extras.git # mirror https://git.savannah.nongnu.org/git/grub-extras.git
git clone https://github.com/somebodykot/grub-improved-luks2-git.git # https://aur.archlinux.org/grub-improved-luks2-git.git 
git clone https://github.com/coreutils/gnulib.git # mirror https://git.savannah.gnu.org/git/gnulib.git 

echo "Compiling grub"

patch -Np1 -i ./grub-improved-luks2-git/add-GRUB_COLOR_variables.patch

# Patch grub-mkconfig to detect Arch Linux initramfs images.
patch -Np1 -i ./grub-improved-luks2-git/detect-archlinux-initramfs.patch

# argon2
patch -Np1 -i ./grub-improved-luks2-git/argon_1.patch
patch -Np1 -i ./grub-improved-luks2-git/argon_2.patch
patch -Np1 -i ./grub-improved-luks2-git/argon_3.patch
patch -Np1 -i ./grub-improved-luks2-git/argon_4.patch
patch -Np1 -i ./grub-improved-luks2-git/argon_5.patch

# make grub-install work with luks2
patch -Np1 -i ./grub-improved-luks2-git/grub-install_luks2.patch

# Fix DejaVuSans.ttf location so that grub-mkfont can create *.pf2 files for starfield theme.
sed 's|/usr/share/fonts/dejavu|/usr/share/fonts/dejavu /usr/share/fonts/TTF|g' -i "configure.ac"

# Modify grub-mkconfig behaviour to silence warnings FS#36275
sed 's| ro | rw |g' -i "util/grub.d/10_linux.in"

# Modify grub-mkconfig behaviour so automatically generated entries read 'Arch Linux' FS#33393
sed 's|GNU/Linux|Linux|' -i "util/grub.d/10_linux.in"

# BUILD
rm -rf ./grub-extras/lua

export GRUB_CONTRIB=./grub-extras
export GNULIB_SRCDIR=./gnulib
CFLAGS=${CFLAGS/-fno-plt}

./bootstrap
mkdir ./build_x86_64-efi
cd ./build_x86_64-efi
../configure --with-platform=efi --target=x86_64 --prefix="/usr" --sbindir="/usr/bin" --sysconfdir="/etc" --enable-boot-time --enable-cache-stats --enable-device-mapper --enable-grub-mkfont --enable-grub-mount --enable-mm-debug --disable-silent-rules --disable-werror  CPPFLAGS="$CPPFLAGS -O2"
make

    
echo "Installing grub"
    
cd ./build_x86_64-efi
make DESTDIR=/ bashcompletiondir=/usr/share/bash-completion/completions install
install -D -m0644 ../grub-improved-luks2-git/grub.default /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB

fi
